# Generated by Django 2.2.3 on 2019-08-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190828_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='news_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='newsid'),
        ),
    ]
