# Generated by Django 2.2 on 2019-07-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineModel',
            fields=[
                ('line_id', models.CharField(max_length=66, primary_key=True, serialize=False, verbose_name='lineID')),
                ('line_token', models.CharField(blank=True, max_length=200, verbose_name='line通行代碼')),
            ],
            options={
                'verbose_name': 'line使用者',
                'verbose_name_plural': 'line使用者',
                'db_table': 'line',
            },
        ),
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('movie_id', models.CharField(max_length=66, primary_key=True, serialize=False, verbose_name='MovieID')),
                ('movie_name', models.CharField(max_length=66, verbose_name='MovieName')),
            ],
            options={
                'verbose_name': 'Movie清單',
                'verbose_name_plural': 'Movie清單',
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='TheaterModel',
            fields=[
                ('theater_id', models.CharField(max_length=66, primary_key=True, serialize=False, verbose_name='TheaterID')),
                ('theater_name', models.CharField(max_length=66, verbose_name='TheaterName')),
            ],
            options={
                'verbose_name': 'Theater清單',
                'verbose_name_plural': 'Theater清單',
                'db_table': 'theater',
            },
        ),
    ]
