# Generated by Django 2.2.3 on 2019-07-15 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineModel',
            fields=[
                ('line_id', models.CharField(max_length=66, primary_key=True, serialize=False, verbose_name='lineID')),
                ('line_token', models.CharField(blank=True, max_length=200, verbose_name='line通行代碼')),
            ],
            options={
                'verbose_name': 'line使用者',
                'verbose_name_plural': 'line使用者',
                'db_table': 'line.line',
            },
        ),
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('movie_id', models.CharField(max_length=66, primary_key=True, serialize=False, verbose_name='MovieID')),
                ('movie_name', models.CharField(max_length=66, verbose_name='MovieName')),
            ],
            options={
                'verbose_name': 'Movie清單',
                'verbose_name_plural': 'Movie清單',
                'db_table': 'line.movie',
            },
        ),
        migrations.CreateModel(
            name='ScheduleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_date', models.DateField()),
                ('movie_id', models.CharField(max_length=66, verbose_name='Sch_MovieID')),
                ('area', models.CharField(max_length=66, verbose_name='ScheduleArea')),
                ('theater_id', models.CharField(max_length=66, verbose_name='Sch_theaterID')),
                ('movie_type', models.CharField(max_length=66, verbose_name='ScheduleType')),
                ('movie_time', models.TimeField(verbose_name='%H:%M')),
            ],
            options={
                'verbose_name': 'schedule清單',
                'verbose_name_plural': 'schedule清單',
                'db_table': 'line.schedule',
            },
        ),
        migrations.CreateModel(
            name='TheaterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater_name', models.CharField(max_length=66, verbose_name='TheaterName')),
                ('theater_area', models.CharField(max_length=66, verbose_name='TheaterArea')),
                ('theater_address', models.CharField(max_length=66, verbose_name='TheaterAddress')),
            ],
            options={
                'verbose_name': 'Theater清單',
                'verbose_name_plural': 'Theater清單',
                'db_table': 'line.theater',
            },
        ),
        migrations.CreateModel(
            name='ControllerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod', models.IntegerField(choices=[(0, '離開'), (1, '本週排名'), (2, '關鍵字查詢')], default=0, null=True, verbose_name='選取模式')),
                ('movie_id', models.CharField(max_length=66, null=True, verbose_name='MovieID')),
                ('date', models.DateField(null=True, verbose_name='選取時間')),
                ('control', models.CharField(max_length=100, null=True, verbose_name='控制器')),
                ('line_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='line', to='line_bot.LineModel', verbose_name='用戶')),
            ],
            options={
                'verbose_name': 'Line 互動訊息',
                'verbose_name_plural': 'Line 互動訊息',
                'db_table': 'line.Controller',
            },
        ),
    ]
