# Generated by Django 2.2.3 on 2019-07-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_date', models.DateField()),
                ('rank', models.IntegerField(verbose_name='Rank')),
                ('movie_id', models.CharField(max_length=66, verbose_name='MovieID')),
                ('movie_name', models.CharField(max_length=66, verbose_name='MovieName')),
            ],
            options={
                'verbose_name': 'rank 列表',
                'verbose_name_plural': 'rank 列表',
                'db_table': 'line.rank',
            },
        ),
        migrations.AlterField(
            model_name='controllermodel',
            name='mod',
            field=models.CharField(max_length=66, null=True, verbose_name='Mod'),
        ),
    ]
