# Generated by Django 2.2.3 on 2019-07-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0002_remove_schedulemodel_schedule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemodel',
            name='movie_date',
            field=models.DateField(),
        ),
    ]
