# Generated by Django 2.2.3 on 2019-07-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0003_auto_20190716_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controllermodel',
            name='mod',
            field=models.IntegerField(null=True, verbose_name='Mod'),
        ),
    ]
