# Generated by Django 2.2.3 on 2019-07-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0004_auto_20190717_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controllermodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='controllermodel',
            name='line_id',
            field=models.CharField(max_length=66, primary_key=True, serialize=False, verbose_name='用戶'),
        ),
        migrations.DeleteModel(
            name='LineModel',
        ),
    ]
