# Generated by Django 2.2.3 on 2019-08-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0005_auto_20190720_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controllermodel',
            name='control',
            field=models.TextField(max_length=100, null=True, verbose_name='控制器'),
        ),
        migrations.AlterField(
            model_name='controllermodel',
            name='line_id',
            field=models.TextField(max_length=66, primary_key=True, serialize=False, verbose_name='用戶'),
        ),
        migrations.AlterField(
            model_name='controllermodel',
            name='movie_id',
            field=models.TextField(max_length=66, null=True, verbose_name='MovieID'),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='movie_id',
            field=models.TextField(max_length=66, primary_key=True, serialize=False, verbose_name='MovieID'),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='movie_name',
            field=models.TextField(max_length=66, verbose_name='MovieName'),
        ),
        migrations.AlterField(
            model_name='rankmodel',
            name='movie_id',
            field=models.TextField(max_length=66, verbose_name='MovieID'),
        ),
        migrations.AlterField(
            model_name='rankmodel',
            name='movie_name',
            field=models.TextField(max_length=66, verbose_name='MovieName'),
        ),
        migrations.AlterField(
            model_name='schedulemodel',
            name='area',
            field=models.TextField(max_length=66, verbose_name='ScheduleArea'),
        ),
        migrations.AlterField(
            model_name='schedulemodel',
            name='movie_id',
            field=models.TextField(max_length=66, verbose_name='Sch_MovieID'),
        ),
        migrations.AlterField(
            model_name='schedulemodel',
            name='movie_type',
            field=models.TextField(max_length=66, verbose_name='ScheduleType'),
        ),
        migrations.AlterField(
            model_name='schedulemodel',
            name='theater_id',
            field=models.TextField(max_length=66, verbose_name='Sch_theaterID'),
        ),
        migrations.AlterField(
            model_name='theatermodel',
            name='theater_address',
            field=models.TextField(max_length=66, verbose_name='TheaterAddress'),
        ),
        migrations.AlterField(
            model_name='theatermodel',
            name='theater_area',
            field=models.TextField(max_length=66, verbose_name='TheaterArea'),
        ),
        migrations.AlterField(
            model_name='theatermodel',
            name='theater_name',
            field=models.TextField(max_length=66, verbose_name='TheaterName'),
        ),
    ]
